import Foundation

// MARK: - Korean Language Pack

extension LocalizedStrings {
    static let korean = LocalizedStrings(
        tabCommands: "명령",
        tabHistory: "히스토리",
        tabClipboard: "클립보드",
        tabTrash: "휴지통",
        tabSettings: "설정",

        executionTerminal: "터미널",
        executionBackground: "백그라운드",
        executionScript: "실행",
        executionSchedule: "일정",

        alertDayBefore: "D-1",
        alertHourBefore: "1시간 전",
        alertThirtyMinBefore: "30분 전",
        alertFiveMinBefore: "5분 전",
        alertNow: "지금!",
        alertPassed: "지남",

        repeatNone: "없음",
        repeatDaily: "매일",
        repeatWeekly: "매주",
        repeatMonthly: "매월",

        historyExecuted: "실행",
        historyBackground: "백그라운드",
        historyScript: "스크립트",
        historyScheduleAlert: "일정 알림",
        historyReminder: "미리 알림",
        historyAdded: "등록",
        historyDeleted: "삭제",
        historyRestored: "복원",
        historyPermanentlyDeleted: "제거",

        buttonClose: "닫기",
        snapToLeft: "왼쪽에 붙이기",
        snapToRight: "오른쪽에 붙이기",
        buttonCancel: "취소",
        buttonConfirm: "확인",
        buttonSave: "저장",
        buttonDelete: "삭제",
        buttonRestore: "복원",
        buttonAdd: "추가",
        buttonEdit: "편집",
        buttonRun: "실행",
        buttonStop: "정지",
        buttonCopy: "복사",
        buttonClear: "지우기",
        buttonExport: "내보내기",
        buttonImport: "가져오기",

        settingsTitle: "설정",
        settingsGeneral: "기본",
        settingsHistoryTab: "히스토리",
        settingsClipboardTab: "클립보드",
        settingsBackup: "백업",
        settingsLanguage: "언어",
        settingsAlwaysOnTop: "항상 위에 표시",
        settingsLaunchAtLogin: "로그인 시 시작",
        settingsBackgroundOpacity: "배경 투명도",
        settingsMaxCount: "최대 개수",
        settingsNotesFolderName: "메모 폴더명",
        settingsAutoHide: "자동 숨기기",
        shortcutConflict: "단축키 등록 실패",
        settingsExportFile: "파일 내보내기",
        settingsImportFile: "파일 가져오기",
        settingsBackupNote: "명령 목록만 백업됩니다",
        settingsLanguagePack: "언어팩",
        settingsExportLanguagePack: "언어팩 견본 내보내기",
        settingsImportLanguagePack: "언어팩 가져오기",

        trashTitle: "휴지통",
        trashEmpty: "비우기",
        trashEmptyMessage: "휴지통이 비어있습니다",
        trashEmptyButton: "비우기",
        trashRestore: "복구",

        commandTitle: "제목",
        commandCommand: "명령",
        commandType: "타입",
        commandTerminalApp: "터미널 앱",
        commandInterval: "실행 간격",
        commandScheduleDate: "일정",
        commandRepeat: "반복",
        commandReminders: "미리 알림",
        commandAddNew: "명령 추가",
        commandEditTitle: "명령 편집",
        commandNoCommands: "명령이 없습니다",
        commandAddFirst: "첫 명령을 추가하세요",

        parameterInputTitle: "파라미터 입력",
        parameterHelpTitle: "파라미터 도움말",
        parameterExample: "예시",
        parameterEnterValue: "값 입력",

        historyTitle: "히스토리",
        historyNoHistory: "기록이 없습니다",
        historyOutput: "출력",
        historyTimes: "회",

        clipboardTitle: "클립보드",
        clipboardNoItems: "클립보드가 비어있습니다",
        clipboardSendToNotes: "메모로 보내기",
        clipboardMakeCommand: "명령으로 만들기",

        alertExportSuccess: "내보내기 완료",
        alertExportFailed: "내보내기 실패",
        alertImportSuccess: "가져오기 완료",
        alertImportFailed: "가져오기 실패",
        alertInvalidFormat: "잘못된 형식",
        alertClipboardEmpty: "클립보드가 비어있음",
        alertCopiedToClipboard: "클립보드에 복사됨",
        alertMergeComplete: "병합 완료",
        alertOverwriteComplete: "덮어쓰기 완료",
        alertSaveFailed: "저장 실패",
        alertReadFailed: "파일 읽기 실패",

        importDialogTitle: "가져오기 방식",
        importMerge: "병합 (기존 데이터 유지)",
        importOverwrite: "덮어쓰기 (기존 데이터 삭제)",

        languagePackExportSuccess: "언어팩 견본이 저장되었습니다",
        languagePackImportSuccess: "언어팩을 적용했습니다",
        languagePackInvalidFormat: "잘못된 언어팩 형식입니다",

        scriptRunning: "실행 중...",
        scriptCompleted: "완료",
        scriptFailed: "실패",
        scriptOutput: "출력",

        secondsUnit: "초",
        minutesUnit: "분",
        hoursUnit: "시간",
        daysUnit: "일",
        manual: "수동",
        running: "실행 중",
        stopped: "정지",
        noOutput: "출력 없음",
        lastRun: "마지막 실행",
        nextRun: "다음 실행",
        interval: "간격",

        commandListTitle: "명령 목록",
        addNewItem: "새 항목 추가",
        dateTime: "날짜/시간",
        executionMethod: "실행 방식",
        commandInput: "명령어",
        commandHelpText: "예: echo {name} → 실행 시 name 입력",
        terminalAppLabel: "터미널 앱",
        intervalLabel: "주기 (초, 0이면 수동)",
        clipboardDetail: "클립보드 상세",
        addToTop: "맨 위에 등록",
        addToBottom: "맨 아래에 등록",
        notification: "알림",
        contextMenuRun: "실행",
        contextMenuEdit: "수정",
        contextMenuCopy: "복사",
        helpSyntax: "기본 문법",
        parameter: "파라미터",
        timeAfter: "후",
        timePassed: "지남",
        clipboardContent: "클립보드 내용",

        groupTitle: "그룹",
        groupAll: "전체",
        groupDefault: "기본",
        groupAddNew: "새 그룹",
        groupEdit: "그룹 편집",
        groupNamePlaceholder: "그룹 이름",
        groupDeleteConfirm: "그룹 삭제 시 명령어는 기본 그룹으로 이동됩니다",
        groupCannotDeleteDefault: "기본 그룹은 삭제할 수 없습니다",
        moveToGroup: "그룹 이동",
        groupColor: "색상",
        groupDeleteTitle: "그룹 삭제",
        groupDeleteMerge: "명령어를 다른 그룹으로 이동",
        groupDeleteWithCommands: "명령어도 함께 삭제",
        groupSelectTarget: "이동할 그룹 선택",
        groupLastGroupCannotDelete: "마지막 그룹은 삭제할 수 없습니다",
        groupNoGroups: "그룹이 없습니다",
        groupCommandCount: "개 명령어",

        favoriteAdd: "즐겨찾기 추가",
        favoriteRemove: "즐겨찾기 해제",

        registerClipboardTitle: "명령으로 등록",
        registerClipboardPosition: "위치",
        registerClipboardPositionTop: "맨 위로",
        registerClipboardPositionBottom: "맨 아래로",
        registerClipboardRegister: "등록",

        apiRequestTitle: "API 요청",
        apiEndpoint: "엔드포인트",
        apiMethod: "메서드",
        apiHeaders: "헤더",
        apiQueryParams: "쿼리 파라미터",
        apiBodyType: "바디 타입",
        apiBodyData: "바디 데이터",
        apiResponse: "응답",
        apiStatusCode: "상태 코드",
        apiAddHeader: "헤더 추가",
        apiAddParam: "파라미터 추가",
        apiExecute: "실행",
        apiLastExecuted: "마지막 실행",
        apiNoResponse: "응답 없음",
        apiLoading: "요청 중...",
        apiAddNew: "새 API 요청",
        apiResponseHeaders: "응답 헤더",
        apiResponseBody: "응답 바디",
        apiExecutionTime: "실행 시간",
        apiRequestInfo: "요청 정보",
        apiCopyResponse: "응답 복사"
    )
}
