import Foundation

// MARK: - Japanese Language Pack

extension LocalizedStrings {
    static let japanese = LocalizedStrings(
        tabCommands: "コマンド",
        tabHistory: "履歴",
        tabClipboard: "クリップボード",
        tabTrash: "ゴミ箱",
        tabSettings: "設定",

        executionTerminal: "ターミナル",
        executionBackground: "バックグラウンド",
        executionScript: "実行",
        executionSchedule: "スケジュール",

        alertDayBefore: "1日前",
        alertHourBefore: "1時間前",
        alertThirtyMinBefore: "30分前",
        alertFiveMinBefore: "5分前",
        alertNow: "今!",
        alertPassed: "経過",

        repeatNone: "なし",
        repeatDaily: "毎日",
        repeatWeekly: "毎週",
        repeatMonthly: "毎月",

        historyExecuted: "実行",
        historyBackground: "バックグラウンド",
        historyScript: "スクリプト",
        historyScheduleAlert: "スケジュール通知",
        historyReminder: "リマインダー",
        historyAdded: "追加",
        historyDeleted: "削除",
        historyRestored: "復元",
        historyPermanentlyDeleted: "完全削除",

        buttonClose: "閉じる",
        buttonCancel: "キャンセル",
        buttonConfirm: "確認",
        buttonSave: "保存",
        buttonDelete: "削除",
        buttonRestore: "復元",
        buttonAdd: "追加",
        buttonEdit: "編集",
        buttonRun: "実行",
        buttonStop: "停止",
        buttonCopy: "コピー",
        buttonClear: "クリア",
        buttonExport: "エクスポート",
        buttonImport: "インポート",

        settingsTitle: "設定",
        settingsGeneral: "一般",
        settingsHistoryTab: "履歴",
        settingsClipboardTab: "クリップボード",
        settingsBackup: "バックアップ",
        settingsLanguage: "言語",
        settingsAlwaysOnTop: "常に最前面",
        settingsLaunchAtLogin: "ログイン時に起動",
        settingsBackgroundOpacity: "背景の透明度",
        settingsMaxCount: "最大件数",
        settingsNotesFolderName: "メモフォルダ名",
        settingsExportFile: "ファイル出力",
        settingsImportFile: "ファイル読込",
        settingsBackupNote: "コマンドのみバックアップされます",
        settingsLanguagePack: "言語パック",
        settingsExportLanguagePack: "テンプレート出力",
        settingsImportLanguagePack: "パック読込",

        trashTitle: "ゴミ箱",
        trashEmpty: "空にする",
        trashEmptyMessage: "ゴミ箱は空です",
        trashEmptyButton: "空にする",
        trashRestore: "復元",

        commandTitle: "タイトル",
        commandCommand: "コマンド",
        commandType: "タイプ",
        commandTerminalApp: "ターミナルアプリ",
        commandInterval: "実行間隔",
        commandScheduleDate: "スケジュール",
        commandRepeat: "繰り返し",
        commandReminders: "リマインダー",
        commandAddNew: "コマンド追加",
        commandEditTitle: "コマンド編集",
        commandNoCommands: "コマンドがありません",
        commandAddFirst: "最初のコマンドを追加してください",

        parameterInputTitle: "パラメータ入力",
        parameterHelpTitle: "パラメータヘルプ",
        parameterExample: "例",
        parameterEnterValue: "値を入力",

        historyTitle: "履歴",
        historyNoHistory: "履歴がありません",
        historyOutput: "出力",
        historyTimes: "回",

        clipboardTitle: "クリップボード",
        clipboardNoItems: "クリップボードは空です",
        clipboardSendToNotes: "メモに送信",
        clipboardMakeCommand: "コマンドにする",

        alertExportSuccess: "エクスポート完了",
        alertExportFailed: "エクスポート失敗",
        alertImportSuccess: "インポート完了",
        alertImportFailed: "インポート失敗",
        alertInvalidFormat: "無効な形式",
        alertClipboardEmpty: "クリップボードが空です",
        alertCopiedToClipboard: "クリップボードにコピー",
        alertMergeComplete: "マージ完了",
        alertOverwriteComplete: "上書き完了",
        alertSaveFailed: "保存失敗",
        alertReadFailed: "ファイル読み込み失敗",

        importDialogTitle: "インポート方法",
        importMerge: "マージ（既存を維持）",
        importOverwrite: "上書き（既存を削除）",

        languagePackExportSuccess: "言語パックテンプレートを保存しました",
        languagePackImportSuccess: "言語パックを適用しました",
        languagePackInvalidFormat: "無効な言語パック形式です",

        scriptRunning: "実行中...",
        scriptCompleted: "完了",
        scriptFailed: "失敗",
        scriptOutput: "出力",

        secondsUnit: "秒",
        minutesUnit: "分",
        hoursUnit: "時間",
        daysUnit: "日",
        manual: "手動",
        running: "実行中",
        stopped: "停止",
        noOutput: "出力なし",
        lastRun: "最終実行",
        nextRun: "次回実行",
        interval: "間隔",

        commandListTitle: "コマンド一覧",
        addNewItem: "新規追加",
        dateTime: "日時",
        executionMethod: "実行方法",
        commandInput: "コマンド",
        commandHelpText: "例: echo {name} → 実行時にname入力",
        terminalAppLabel: "ターミナルアプリ",
        intervalLabel: "間隔（秒、0は手動）",
        clipboardDetail: "クリップボード詳細",
        addToTop: "先頭に追加",
        addToBottom: "末尾に追加",
        notification: "通知",
        contextMenuRun: "実行",
        contextMenuEdit: "編集",
        contextMenuCopy: "コピー",
        helpSyntax: "基本文法",
        parameter: "パラメータ",
        timeAfter: "後",
        timePassed: "経過",
        clipboardContent: "クリップボード内容",

        groupTitle: "グループ",
        groupAll: "すべて",
        groupDefault: "デフォルト",
        groupAddNew: "新規グループ",
        groupEdit: "グループ編集",
        groupNamePlaceholder: "グループ名",
        groupDeleteConfirm: "コマンドはデフォルトグループに移動されます",
        groupCannotDeleteDefault: "デフォルトグループは削除できません",
        moveToGroup: "グループに移動",
        groupColor: "色",
        groupDeleteTitle: "グループ削除",
        groupDeleteMerge: "コマンドを別のグループに移動",
        groupDeleteWithCommands: "コマンドも一緒に削除",
        groupSelectTarget: "移動先グループを選択",
        groupLastGroupCannotDelete: "最後のグループは削除できません",
        groupNoGroups: "グループがありません",
        groupCommandCount: "コマンド",

        favoriteAdd: "お気に入りに追加",
        favoriteRemove: "お気に入りから削除",

        registerClipboardTitle: "コマンドとして登録",
        registerClipboardPosition: "位置",
        registerClipboardPositionTop: "一番上",
        registerClipboardPositionBottom: "一番下",
        registerClipboardRegister: "登録",

        apiRequestTitle: "APIリクエスト",
        apiEndpoint: "エンドポイント",
        apiMethod: "メソッド",
        apiHeaders: "ヘッダー",
        apiQueryParams: "クエリパラメータ",
        apiBodyType: "ボディタイプ",
        apiBodyData: "ボディデータ",
        apiResponse: "レスポンス",
        apiStatusCode: "ステータスコード",
        apiAddHeader: "ヘッダー追加",
        apiAddParam: "パラメータ追加",
        apiExecute: "実行",
        apiLastExecuted: "最終実行",
        apiNoResponse: "レスポンスなし",
        apiAddNew: "新規APIリクエスト",
        apiResponseHeaders: "レスポンスヘッダー",
        apiResponseBody: "レスポンスボディ",
        apiExecutionTime: "実行時間",
        apiRequestInfo: "リクエスト情報",
        apiCopyResponse: "レスポンスをコピー"
    )

    static func forLanguage(_ language: Language) -> LocalizedStrings {
        switch language {
        case .korean: return .korean
        case .english: return .english
        case .japanese: return .japanese
        }
    }
}
