import Foundation

// MARK: - English Language Pack

extension LocalizedStrings {
    static let english = LocalizedStrings(
        tabCommands: "Commands",
        tabHistory: "History",
        tabClipboard: "Clipboard",
        tabTrash: "Trash",
        tabSettings: "Settings",

        executionTerminal: "Terminal",
        executionBackground: "Background",
        executionScript: "Script",
        executionSchedule: "Schedule",

        alertDayBefore: "D-1",
        alertHourBefore: "1 hour",
        alertThirtyMinBefore: "30 min",
        alertFiveMinBefore: "5 min",
        alertNow: "Now!",
        alertPassed: "Passed",

        repeatNone: "None",
        repeatDaily: "Daily",
        repeatWeekly: "Weekly",
        repeatMonthly: "Monthly",

        historyExecuted: "Executed",
        historyBackground: "Background",
        historyScript: "Script",
        historyScheduleAlert: "Schedule Alert",
        historyReminder: "Reminder",
        historyAdded: "Added",
        historyDeleted: "Deleted",
        historyRestored: "Restored",
        historyPermanentlyDeleted: "Removed",

        buttonClose: "Close",
        buttonCancel: "Cancel",
        buttonConfirm: "OK",
        buttonSave: "Save",
        buttonDelete: "Delete",
        buttonRestore: "Restore",
        buttonAdd: "Add",
        buttonEdit: "Edit",
        buttonRun: "Run",
        buttonStop: "Stop",
        buttonCopy: "Copy",
        buttonClear: "Clear",
        buttonExport: "Export",
        buttonImport: "Import",

        settingsTitle: "Settings",
        settingsGeneral: "General",
        settingsHistoryTab: "History",
        settingsClipboardTab: "Clipboard",
        settingsBackup: "Backup",
        settingsLanguage: "Language",
        settingsAlwaysOnTop: "Always on Top",
        settingsLaunchAtLogin: "Launch at Login",
        settingsBackgroundOpacity: "Background Opacity",
        settingsMaxCount: "Max Count",
        settingsNotesFolderName: "Notes Folder",
        settingsExportFile: "Export File",
        settingsImportFile: "Import File",
        settingsBackupNote: "Only commands are backed up",
        settingsLanguagePack: "Language Pack",
        settingsExportLanguagePack: "Export Template",
        settingsImportLanguagePack: "Import Pack",

        trashTitle: "Trash",
        trashEmpty: "Empty",
        trashEmptyMessage: "Trash is empty",
        trashEmptyButton: "Empty",

        commandTitle: "Title",
        commandCommand: "Command",
        commandType: "Type",
        commandTerminalApp: "Terminal App",
        commandInterval: "Interval",
        commandScheduleDate: "Schedule",
        commandRepeat: "Repeat",
        commandReminders: "Reminders",
        commandAddNew: "Add Command",
        commandEditTitle: "Edit Command",
        commandNoCommands: "No commands",
        commandAddFirst: "Add your first command",

        parameterInputTitle: "Enter Parameters",
        parameterHelpTitle: "Parameter Help",
        parameterExample: "Example",
        parameterEnterValue: "Enter value",

        historyTitle: "History",
        historyNoHistory: "No history",
        historyOutput: "Output",
        historyTimes: "times",

        clipboardTitle: "Clipboard",
        clipboardNoItems: "Clipboard is empty",
        clipboardSendToNotes: "Send to Notes",
        clipboardMakeCommand: "Make Command",

        alertExportSuccess: "Export complete",
        alertExportFailed: "Export failed",
        alertImportSuccess: "Import complete",
        alertImportFailed: "Import failed",
        alertInvalidFormat: "Invalid format",
        alertClipboardEmpty: "Clipboard is empty",
        alertCopiedToClipboard: "Copied to clipboard",
        alertMergeComplete: "Merge complete",
        alertOverwriteComplete: "Overwrite complete",
        alertSaveFailed: "Save failed",
        alertReadFailed: "Failed to read file",

        importDialogTitle: "Import Method",
        importMerge: "Merge (keep existing)",
        importOverwrite: "Overwrite (delete existing)",

        languagePackExportSuccess: "Language pack template saved",
        languagePackImportSuccess: "Language pack applied",
        languagePackInvalidFormat: "Invalid language pack format",

        scriptRunning: "Running...",
        scriptCompleted: "Completed",
        scriptFailed: "Failed",
        scriptOutput: "Output",

        secondsUnit: "sec",
        minutesUnit: "min",
        hoursUnit: "hour",
        daysUnit: "day",
        manual: "Manual",
        running: "Running",
        stopped: "Stopped",
        noOutput: "No output",
        lastRun: "Last run",
        nextRun: "Next run",
        interval: "Interval",

        commandListTitle: "Command List",
        addNewItem: "Add New Item",
        dateTime: "Date/Time",
        executionMethod: "Execution Method",
        commandInput: "Command",
        commandHelpText: "Ex: echo {name} → enter name at runtime",
        terminalAppLabel: "Terminal App",
        intervalLabel: "Interval (sec, 0 for manual)",
        clipboardDetail: "Clipboard Detail",
        addToTop: "Add to Top",
        addToBottom: "Add to Bottom",
        notification: "Notification",
        contextMenuRun: "Run",
        contextMenuEdit: "Edit",
        contextMenuCopy: "Copy",
        helpSyntax: "Basic Syntax",
        parameter: "Parameter",
        timeAfter: "later",
        timePassed: "ago",
        clipboardContent: "Clipboard Content",

        groupTitle: "Group",
        groupAll: "All",
        groupDefault: "Default",
        groupAddNew: "New Group",
        groupEdit: "Edit Group",
        groupNamePlaceholder: "Group name",
        groupDeleteConfirm: "Commands will be moved to default group",
        groupCannotDeleteDefault: "Cannot delete default group",
        moveToGroup: "Move to Group",
        groupColor: "Color",
        groupDeleteTitle: "Delete Group",
        groupDeleteMerge: "Move commands to another group",
        groupDeleteWithCommands: "Delete commands too",
        groupSelectTarget: "Select target group",
        groupLastGroupCannotDelete: "Cannot delete the last group",
        groupNoGroups: "No groups",
        groupCommandCount: "commands",

        favoriteAdd: "Add to Favorites",
        favoriteRemove: "Remove from Favorites"
    )
}
